// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVt-02Ix0eO76-Ng45VNbxFFDQGEy9Z3Q',
    appId: '1:149936110564:web:d9fc0a05edee3b4ce325f1',
    messagingSenderId: '149936110564',
    projectId: 'sgtours-845a9',
    authDomain: 'sgtours-845a9.firebaseapp.com',
    databaseURL:
        'https://sgtours-845a9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sgtours-845a9.appspot.com',
    measurementId: 'G-J18EY8C21D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBiFOZ7OZx-6yk2txfzVJ2XVj6xKTyyig',
    appId: '1:149936110564:android:d4b9b98e70a141cae325f1',
    messagingSenderId: '149936110564',
    projectId: 'sgtours-845a9',
    databaseURL:
        'https://sgtours-845a9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sgtours-845a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHpZ-1jijKSSGv4BUbuYQGZb5MqGmpya0',
    appId: '1:149936110564:ios:3d2ef8cdfb1da2fae325f1',
    messagingSenderId: '149936110564',
    projectId: 'sgtours-845a9',
    databaseURL:
        'https://sgtours-845a9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sgtours-845a9.appspot.com',
    iosClientId:
        '149936110564-0n6sn53assq1tpqf0lhr78bmrhpf780f.apps.googleusercontent.com',
    iosBundleId: 'com.example.sgtours',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHpZ-1jijKSSGv4BUbuYQGZb5MqGmpya0',
    appId: '1:149936110564:ios:3d2ef8cdfb1da2fae325f1',
    messagingSenderId: '149936110564',
    projectId: 'sgtours-845a9',
    databaseURL:
        'https://sgtours-845a9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sgtours-845a9.appspot.com',
    iosClientId:
        '149936110564-0n6sn53assq1tpqf0lhr78bmrhpf780f.apps.googleusercontent.com',
    iosBundleId: 'com.example.sgtours',
  );
}
